@startuml

hide circle
skinparam inetype ortho

entity User {
    +id: uuid
    --
    ~iconId: int
}
note right of User: idはsocketIdに対応

entity Icon {
    +id: int
    --
    #description: string
}

entity Room {
    +id: uuid
    --
    ~status: int
    #roomKey: string
    #title: string
}

entity RoomStatus {
    +id: int
    --
    #description: string
}

entity Topic {
    +id: int
    ~roomId: uuid
    --
    #title string
    #description: string
    #state: int
    githubUrl: string
    slideUrl: string
    productUrl: string
}

entity TopicState {
    +id: int
    --
    #description: string
}

entity ChatItem {
    +id: uuid
    --
    ~roomId: uuid
    ~topicId: int
    ~userId: uuid
    ~typeId: int
    ~targetId uuid
    content: string
    #timestamp: int
    #createdAt: timestamp
}
note bottom of ChatItem
 あるChatItemがその他のChatItemに対する返信の場合、
 返信先のChatItemのidがtargetIdに入る。
 返信でないChatItemのtargetIdにはNULLが入る。
 また、複数のChatItemが同じChatItemに返信することもできる。
end note

entity ChatItemType {
    +id: int
    --
    #description: string
}

entity Stamp {
    +id: int
    --
    ~roomId: uuid
    ~topicId: int
    ~userId: uuid
    #createdAt: timestamp
}

User }o--|| Icon
Room }o--|| RoomStatus
Topic }|--|| Room
Topic }o--|| TopicState
ChatItem }o--|| Topic
ChatItem }o--|| User
ChatItem }o--|| ChatItemType
ChatItem |o--o{ ChatItem
Stamp }o--|| Topic
Stamp }o--|| User

entity Example {
    +primary_key: type
    --
    ~foreign_key: type
    #not null: type
}
note bottom: 上からそれぞれ<<PK>>, <<FK>>, <<NOT NULL>>を表す記号

@enduml